blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ è³ªå•ãƒ»ç›¸è«‡
    url: https://github.com/TkymHrt/next-payload-starter/discussions
    about: ãƒã‚°å ±å‘Šã‚„æ©Ÿèƒ½ãƒªã‚¯ã‚¨ã‚¹ãƒˆä»¥å¤–ã®è³ªå•ã¯Discussionsã‚’ã”åˆ©ç”¨ãã ã•ã„
